name: Build Keyframe Curator Apps
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pyinstaller opencv-python-headless numpy
      
      - name: Build Windows app
        run: pyinstaller --onefile --windowed --name "Keyframe_Curator_Windows" main_app.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: dist/Keyframe_Curator_Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pyinstaller opencv-python-headless numpy
      
      - name: Build macOS app
        run: pyinstaller --onedir --windowed --name "Keyframe_Curator_Mac" main_app.py
      
      - name: Create zip
        run: |
          cd dist
          zip -r Keyframe_Curator_Mac.zip "Keyframe_Curator_Mac.app"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/Keyframe_Curator_Mac.zip
